"""Link invoices to bookings and enable tenant financials

Revision ID: 07fee01dee8a
Revises: 7a86d245a1bb
Create Date: 2026-06-22 12:54:12.279109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07fee01dee8a'
down_revision: Union[str, Sequence[str], None] = '7a86d245a1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_booking_id'), 'invoices', ['booking_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_booking_id'), table_name='invoices')
    op.drop_column('invoices', 'booking_id')
    # ### end Alembic commands ###
