"""add_job_title_to_users

Revision ID: 0f85e8aaa282
Revises: fb1756fb095d
Create Date: 2026-07-06 18:21:06.500260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f85e8aaa282'
down_revision: Union[str, Sequence[str], None] = 'fb1756fb095d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    # ### end Alembic commands ###
