"""add_role_templates_table

Revision ID: 17e5ab20ce42
Revises: 0f85e8aaa282
Create Date: 2026-07-06 21:28:22.381087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17e5ab20ce42'
down_revision: Union[str, Sequence[str], None] = '0f85e8aaa282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_templates_id'), 'role_templates', ['id'], unique=False)
    op.create_index(op.f('ix_role_templates_tenant_id'), 'role_templates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_templates_tenant_id'), table_name='role_templates')
    op.drop_index(op.f('ix_role_templates_id'), table_name='role_templates')
    op.drop_table('role_templates')
    # ### end Alembic commands ###
