"""remove_quotations_table

Revision ID: 2ace094582bc
Revises: 7e5ad7c39883
Create Date: 2026-07-01 19:55:22.241347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ace094582bc'
down_revision: Union[str, Sequence[str], None] = '7e5ad7c39883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotations_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_share_token'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_table('quotations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'sent', 'accepted', 'rejected', 'expired', name='quotationstatus'), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('share_token', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('share_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('pickup_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('return_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('daily_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('terms_and_conditions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('quotations_booking_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('quotations_client_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('quotations_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('quotations_vehicle_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('quotations_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('quotations_booking_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_quotations_share_token'), 'quotations', ['share_token'], unique=True)
    op.create_index(op.f('ix_quotations_id'), 'quotations', ['id'], unique=False)
    # ### end Alembic commands ###
