"""add_task_isolation_and_unassigned_pool

Revision ID: 3912c59cdfba
Revises: d18f90347f1a
Create Date: 2026-07-07 13:39:06.860374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3912c59cdfba'
down_revision: Union[str, Sequence[str], None] = 'd18f90347f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('requires_role', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tasks_location_id'), 'tasks', ['location_id'], unique=False)
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_location_id'), table_name='tasks')
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'is_archived')
    op.drop_column('tasks', 'requires_role')
    op.drop_column('tasks', 'location_id')
    # ### end Alembic commands ###
