"""add email and phone verification columns to users

Revision ID: 41d5553f0b25
Revises: 5badfccb6366
Create Date: 2026-07-19 10:23:29.834088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d5553f0b25'
down_revision: Union[str, Sequence[str], None] = '5badfccb6366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
