"""fix_circular_booking_quotation_fk

Revision ID: 42724b5be0af
Revises: fddc481bdc77
Create Date: 2026-06-30 22:07:01.076592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42724b5be0af'
down_revision: Union[str, Sequence[str], None] = 'fddc481bdc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_quotation_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'quotation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bookings_quotation_id_fkey'), 'bookings', 'quotations', ['quotation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
