"""add failed login attempts to users

Revision ID: 4ed88f9ea86d
Revises: 41d5553f0b25
Create Date: 2026-07-19 10:27:15.318340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed88f9ea86d'
down_revision: Union[str, Sequence[str], None] = '41d5553f0b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
