"""add_insurance_number_to_vehicles

Revision ID: 50d6cda3c1ef
Revises: ece3396b4c2f
Create Date: 2026-07-08 10:50:07.300824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d6cda3c1ef'
down_revision: Union[str, Sequence[str], None] = 'ece3396b4c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
