"""Add user UI preferences

Revision ID: 5fa2f206cc82
Revises: 66d14d3f9e95
Create Date: 2026-07-15 10:32:28.735287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa2f206cc82'
down_revision: Union[str, Sequence[str], None] = '66d14d3f9e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_preference', sa.String(length=20), server_default='system', nullable=True))
    op.add_column('users', sa.Column('density_preference', sa.String(length=20), server_default='comfortable', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'density_preference')
    op.drop_column('users', 'theme_preference')
    # ### end Alembic commands ###
