"""add signature path to contracts

Revision ID: 63be7ab9060e
Revises: 50d6cda3c1ef
Create Date: 2026-07-09 21:46:22.203097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63be7ab9060e'
down_revision: Union[str, Sequence[str], None] = '50d6cda3c1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('signature_image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'signature_image_path')
    # ### end Alembic commands ###
