"""add_tenant_recovery_audit_fields

Revision ID: 66d14d3f9e95
Revises: 75df16253d5c
Create Date: 2026-07-12 20:01:13.430666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d14d3f9e95'
down_revision: Union[str, Sequence[str], None] = '75df16253d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('last_reset_request_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('email_change_cooldown_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('admin_email_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('admin_changed_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'users', ['admin_changed_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'admin_changed_by_user_id')
    op.drop_column('tenants', 'admin_email_changed_at')
    op.drop_column('tenants', 'email_change_cooldown_until')
    op.drop_column('tenants', 'last_reset_request_at')
    # ### end Alembic commands ###
