"""add_user_invite_lifecycle_fields

Revision ID: 6e1391068e54
Revises: 5fa2f206cc82
Create Date: 2026-07-15 14:29:18.596941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1391068e54'
down_revision: Union[str, Sequence[str], None] = '5fa2f206cc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_onboarded', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_onboarded')
    op.drop_column('users', 'invite_expires_at')
    op.drop_column('users', 'invite_token')
    # ### end Alembic commands ###
