"""add_share_tokens_to_invoices

Revision ID: 7498c36a68ec
Revises: 8e32e3ae5bca
Create Date: 2026-06-29 16:57:34.726108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7498c36a68ec'
down_revision: Union[str, Sequence[str], None] = '8e32e3ae5bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('share_token', sa.String(length=36), nullable=True))
    op.add_column('invoices', sa.Column('share_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_invoices_share_token'), 'invoices', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_share_token'), table_name='invoices')
    op.drop_column('invoices', 'share_token_expires_at')
    op.drop_column('invoices', 'share_token')
    # ### end Alembic commands ###
