"""add_tenant_lifecycle_columns

Revision ID: 8018bdc8e689
Revises: 6a3829611d92
Create Date: 2026-07-12 12:03:25.257802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8018bdc8e689'
down_revision: Union[str, Sequence[str], None] = '6a3829611d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenants', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('suspension_reason', sa.Text(), nullable=True))
    op.drop_constraint(op.f('tenants_email_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_email_key'), 'tenants', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'suspension_reason')
    op.drop_column('tenants', 'suspended_at')
    op.drop_column('tenants', 'is_archived')
    # ### end Alembic commands ###
