"""add quotation_sent_at to bookings

Revision ID: 8e32e3ae5bca
Revises: cc8f0fabbb25
Create Date: 2026-06-29 14:56:07.952642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e32e3ae5bca'
down_revision: Union[str, Sequence[str], None] = 'cc8f0fabbb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('quotation_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'quotation_sent_at')
    # ### end Alembic commands ###
