"""Add destination and location fields to bookings

Revision ID: a5e7ae278d5e
Revises: 79d1d86e56cb
Create Date: 2026-06-22 15:59:17.745693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e7ae278d5e'
down_revision: Union[str, Sequence[str], None] = '79d1d86e56cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('pickup_location', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('return_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'return_location')
    op.drop_column('bookings', 'pickup_location')
    op.drop_column('bookings', 'destination')
    # ### end Alembic commands ###
