"""add original_end_date to bookings

Revision ID: a906bd02fd46
Revises: c4dc848cb02a
Create Date: 2026-07-17 00:58:55.240701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a906bd02fd46'
down_revision: Union[str, Sequence[str], None] = 'c4dc848cb02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('original_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'original_end_date')
    # ### end Alembic commands ###
