"""add owner_id to tenants for agency owner

Revision ID: aa49a23fcdd4
Revises: e162ea210769
Create Date: 2026-07-19 17:56:36.951430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa49a23fcdd4'
down_revision: Union[str, Sequence[str], None] = 'e162ea210769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tenants_owner_id'), 'tenants', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'tenants', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('is_super_tenant_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_tenant_admin')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_index(op.f('ix_tenants_owner_id'), table_name='tenants')
    op.drop_column('tenants', 'owner_id')
    # ### end Alembic commands ###
