"""add_denormalized_admin_columns

Revision ID: acd74d6686ea
Revises: dca355ba36d5
Create Date: 2026-07-12 13:29:20.408352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd74d6686ea'
down_revision: Union[str, Sequence[str], None] = 'dca355ba36d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('admin_name', sa.String(length=150), nullable=True))
    op.add_column('tenants', sa.Column('admin_email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('admin_phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'admin_phone')
    op.drop_column('tenants', 'admin_email')
    op.drop_column('tenants', 'admin_name')
    # ### end Alembic commands ###
