"""create_quotations_table

Revision ID: c8f35416d892
Revises: 6daa089eab92
Create Date: 2026-06-30 13:20:43.232786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8f35416d892'
down_revision: Union[str, Sequence[str], None] = '6daa089eab92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.add_column('quotations', sa.Column('pickup_location', sa.String(), nullable=True))
    op.add_column('quotations', sa.Column('return_location', sa.String(), nullable=True))
    op.add_column('quotations', sa.Column('destination', sa.String(), nullable=True))
    op.alter_column('quotations', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotations', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotations', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('quotations', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('quotations', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('quotations', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quotations', 'status',
               existing_type=postgresql.ENUM('draft', 'sent', 'accepted', 'rejected', 'expired', name='quotationstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quotations', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_quotations_booking_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_client_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_vehicle_id'), table_name='quotations')
    op.drop_constraint(op.f('quotations_client_id_fkey'), 'quotations', type_='foreignkey')
    op.drop_constraint(op.f('quotations_vehicle_id_fkey'), 'quotations', type_='foreignkey')
    op.create_foreign_key(None, 'quotations', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quotations', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.drop_column('quotations', 'quotation_number')
    op.drop_column('quotations', 'valid_until')
    op.drop_column('quotations', 'converted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('quotations', sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('quotations', sa.Column('quotation_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.create_foreign_key(op.f('quotations_vehicle_id_fkey'), 'quotations', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('quotations_client_id_fkey'), 'quotations', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_quotations_vehicle_id'), 'quotations', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=True)
    op.create_index(op.f('ix_quotations_client_id'), 'quotations', ['client_id'], unique=False)
    op.create_index(op.f('ix_quotations_booking_id'), 'quotations', ['booking_id'], unique=False)
    op.alter_column('quotations', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotations', 'status',
               existing_type=postgresql.ENUM('draft', 'sent', 'accepted', 'rejected', 'expired', name='quotationstatus'),
               server_default=sa.text("'draft'::quotationstatus"),
               existing_nullable=False)
    op.alter_column('quotations', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'KES'::character varying"),
               existing_nullable=False)
    op.alter_column('quotations', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('quotations', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('quotations', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('quotations', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quotations', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quotations', 'destination')
    op.drop_column('quotations', 'return_location')
    op.drop_column('quotations', 'pickup_location')
    op.alter_column('bookings', 'currency_code',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'KES'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
