"""add_tenant_id_to_tasks

Revision ID: d18f90347f1a
Revises: 17992a739b0f
Create Date: 2026-07-07 11:00:36.716193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18f90347f1a'
down_revision: Union[str, Sequence[str], None] = '17992a739b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_column('tasks', 'tenant_id')
    # ### end Alembic commands ###
