"""add_tenant_search_vault_index

Revision ID: dca355ba36d5
Revises: 8018bdc8e689
Create Date: 2026-07-12 12:32:26.962077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca355ba36d5'
down_revision: Union[str, Sequence[str], None] = '8018bdc8e689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenant_profiles_company_name'), 'tenant_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_tenant_profiles_tax_number'), 'tenant_profiles', ['tax_number'], unique=False)
    op.create_index('ix_tenants_search_vault', 'tenants', ['is_archived', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenants_search_vault', table_name='tenants')
    op.drop_index(op.f('ix_tenant_profiles_tax_number'), table_name='tenant_profiles')
    op.drop_index(op.f('ix_tenant_profiles_company_name'), table_name='tenant_profiles')
    # ### end Alembic commands ###
