"""add avatar and compliance image urls to users

Revision ID: e162ea210769
Revises: af963ccc713b
Create Date: 2026-07-19 13:39:46.264036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e162ea210769'
down_revision: Union[str, Sequence[str], None] = 'af963ccc713b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('id_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dl_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dl_image_url')
    op.drop_column('users', 'id_image_url')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
