"""add_insurance_number_to_vehicles

Revision ID: ece3396b4c2f
Revises: 207ccc371314
Create Date: 2026-07-07 23:47:42.930262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ece3396b4c2f'
down_revision: Union[str, Sequence[str], None] = '207ccc371314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('insurance_number', sa.String(), nullable=True))
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('available', 'rented', 'maintenance', 'retired', 'pending_activation', name='vehiclestatus'),
               server_default='pending_activation',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('available', 'rented', 'maintenance', 'retired', 'pending_activation', name='vehiclestatus'),
               server_default=sa.text("'available'::vehiclestatus"),
               existing_nullable=False)
    op.drop_column('vehicles', 'insurance_number')
    # ### end Alembic commands ###
