"""add_booking_quotation_relationships

Revision ID: fddc481bdc77
Revises: c8f35416d892
Create Date: 2026-06-30 21:04:42.980001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fddc481bdc77'
down_revision: Union[str, Sequence[str], None] = 'c8f35416d892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('quotation_id', sa.Integer(), nullable=True))
    op.alter_column('bookings', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('bookings', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'active', 'completed', 'cancelled', 'no_show', name='bookingstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bookings', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_foreign_key(None, 'bookings', 'quotations', ['quotation_id'], ['id'], ondelete='SET NULL')
    op.add_column('quotations', sa.Column('daily_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('quotations', sa.Column('terms_and_conditions', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'quotations', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotations', type_='unique')
    op.drop_column('quotations', 'terms_and_conditions')
    op.drop_column('quotations', 'daily_rate')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.alter_column('bookings', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('pending', 'confirmed', 'active', 'completed', 'cancelled', 'no_show', name='bookingstatus'),
               server_default=sa.text("'pending'::bookingstatus"),
               existing_nullable=False)
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('bookings', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('bookings', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('bookings', 'quotation_id')
    op.drop_column('bookings', 'daily_rate')
    # ### end Alembic commands ###
