"""add_auto_renew_billing_cycle_and_pending_verification

Revision ID: fed3e970ec43
Revises: cb0ad871e9f6
Create Date: 2026-07-21 11:22:51.128663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed3e970ec43'
down_revision: Union[str, Sequence[str], None] = 'cb0ad871e9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('billing_cycle', sa.String(length=20), server_default='monthly', nullable=False))
    op.add_column('tenants', sa.Column('auto_renew', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenants', sa.Column('custom_vehicle_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'custom_vehicle_limit')
    op.drop_column('tenants', 'auto_renew')
    op.drop_column('tenants', 'billing_cycle')
    # ### end Alembic commands ###
